import { db } from "@/lib/db";

/**
 * DukaFlow — KRA e-invoice email builder.
 *
 * One source of truth for the electronic-tax-invoice email body, shared by:
 *  • the auto-send that fires in POST /api/sales when a sale is KRA-verified
 *    and the customer has an email on file, and
 *  • the manual "Email e-invoice" action on the Receipts screen.
 *
 * The mock mailer persists to SmsLog (channel "Email", type "Invoice") so the
 * full mail history stays auditable in the Messages screen — swap this for
 * Resend/SES/Nodemailer in production without touching the callers.
 */

export interface InvoiceEmailInput {
  receiptNo: string;
  createdAt: Date;
  storeName: string;
  staffName: string;
  paymentMethod: string;
  customerName: string;
  customerPhone?: string | null;
  subtotal: number;
  discount: number;
  vat: number;
  total: number;
  kraStatus: string;
  cuInvoiceNumber: string | null;
  kraPin: string;
  companyName: string;
  items: { name: string; qty: number; unitPrice: number; total: number }[];
}

const fmtKES = (n: number) => `KES ${Math.round(n).toLocaleString("en-KE")}`;

export function buildInvoiceEmail(s: InvoiceEmailInput): { subject: string; body: string } {
  const when = new Date(s.createdAt).toLocaleString("en-KE", {
    day: "2-digit", month: "short", year: "numeric", hour: "2-digit", minute: "2-digit",
  });

  const subject = `${s.companyName} — Tax Invoice ${s.receiptNo} (KRA eTIMS verified)`;

  const itemLines = s.items
    .map((i) => `  • ${i.qty} × ${i.name} @ ${fmtKES(i.unitPrice)} — ${fmtKES(i.total)}`)
    .join("\n");

  const lines = [
    `Karibu ${s.customerName},`,
    "",
    `Thank you for shopping with ${s.companyName}. Your electronic tax invoice is below and has been transmitted to the Kenya Revenue Authority via eTIMS.`,
    "",
    `Invoice:    ${s.receiptNo}`,
    `CU Number:  ${s.cuInvoiceNumber ?? "—"}`,
    `KRA PIN:    ${s.kraPin}`,
    `Date:       ${when}`,
    `Store:      ${s.storeName} • Served by ${s.staffName}`,
    `Payment:    ${s.paymentMethod}`,
    `Billed to:  ${s.customerName}${s.customerPhone ? ` (${s.customerPhone})` : ""}`,
    "",
    "Items",
    itemLines,
    "",
    `Subtotal:   ${fmtKES(s.subtotal)}`,
    ...(s.discount > 0 ? [`Discount:   −${fmtKES(s.discount)}`] : []),
    `VAT 16%:    ${fmtKES(s.vat)}`,
    `TOTAL:      ${fmtKES(s.total)}`,
    "",
    `Status:     ${s.kraStatus === "Verified" ? "✔ KRA eTIMS Verified — scan the QR on your receipt to validate with KRA" : "⏳ Awaiting KRA verification"}`,
    "",
    "This email was generated by DukaFlow POS. Keep it for your records — it is a valid electronic tax invoice under the Tax Procedures Act.",
    "Asante tena!",
  ];

  return { subject, body: lines.join("\n") };
}

/** Loads a sale (with items/store/customer) and renders the email in one call. */
export async function buildInvoiceEmailForSale(saleId: number) {
  const sale = await db.sale.findUnique({
    where: { id: saleId },
    include: {
      items: true,
      store: { select: { name: true } },
      customer: { select: { name: true, phone: true, email: true } },
    },
  });
  if (!sale) return null;

  const settings = await db.settings.findFirst();
  const { subject, body } = buildInvoiceEmail({
    receiptNo: sale.receiptNo,
    createdAt: sale.createdAt,
    storeName: sale.store.name,
    staffName: sale.staffName,
    paymentMethod: sale.paymentMethod,
    customerName: sale.customer?.name ?? "Walk-in customer",
    customerPhone: sale.customer?.phone ?? null,
    subtotal: sale.subtotal,
    discount: sale.discount,
    vat: sale.vat,
    total: sale.total,
    kraStatus: sale.kraStatus,
    cuInvoiceNumber: sale.cuInvoiceNumber,
    kraPin: settings?.kraPin ?? "P051234567A",
    companyName: settings?.companyName ?? "DukaFlow Ltd",
    items: sale.items.map((i) => ({ name: i.name, qty: i.qty, unitPrice: i.unitPrice, total: i.total })),
  });

  return { sale, settings, subject, body, customerEmail: sale.customer?.email || "" };
}
