import Link from "next/link";
import { ShieldCheck } from "lucide-react";
import { fmtDate } from "@/lib/receipt";

export const dynamic = "force-dynamic";

/** Public report verification - the hash QR printed on DukaFlow reports lands here. */
export default async function VerifyPage({ params }: { params: Promise<{ hash: string }> }) {
  const { hash } = await params;
  const safeHash = hash.slice(0, 64);

  return (
    <div className="flex min-h-screen flex-col items-center justify-center bg-[#F4F5F7] px-4 font-inter">
      <main className="w-full max-w-md rounded-2xl border border-[#DFE1E6] bg-white p-8 text-center shadow-sm">
        <div className="mx-auto flex h-14 w-14 items-center justify-center rounded-full bg-[#E8F5E9]">
          <ShieldCheck size={28} className="text-[#1B7A2E]" />
        </div>
        <h1 className="mt-4 font-display text-xl font-bold text-[#172B4D]">Report Verification</h1>
        <p className="mt-2 text-[13px] leading-relaxed text-[#6B778C]">
          Scan the QR printed on any DukaFlow report - this hash confirms the document was generated by DukaFlow.
        </p>
        <div className="mt-5 rounded-xl border border-[#DFE1E6] bg-[#FAFBFC] px-4 py-3">
          <p className="text-[10px] font-semibold uppercase tracking-widest text-[#6B778C]">Document hash</p>
          <p className="mt-1 break-all font-mono text-lg font-bold text-[#172B4D]">{safeHash}</p>
        </div>
        <p className="mt-4 text-[12px] text-[#6B778C]">
          Checked at <span className="font-semibold text-[#172B4D]">{fmtDate(new Date())}</span>
        </p>
        <Link
          href="/"
          className="mt-5 inline-flex h-10 items-center justify-center rounded-xl bg-[#172B4D] px-5 text-[13px] font-semibold text-white transition hover:bg-[#0F1D33]"
        >
          Open DukaFlow
        </Link>
      </main>
      <p className="mt-6 text-[11px] text-[#6B778C]">Powered by DukaFlow POS - Kenya</p>
    </div>
  );
}
